### ISSUE TITLE
Less configuration

### ISSUE THREAD

**Issue by ridiculous** [mzaccari/rake-task-migrations#1]
Hey @mzaccari, I like the gem! I was about do create something similar, because I couldn't find a gem that offered "chore" type migrations, which generally just need to be run once. 

What I don't get for these types of migrations is the ability to run the migration multiple times (e.g. on every deploy). At that point, is it really a migration? Seems more like a regular rake task. If you removed this ability, the code would be much simpler and the need for configuration goes away. The lib I wrote that was similar to this, just found all the rake tasks that were namespaced under "chores" and saved it to the db after a successful run (like "schema_migrations"). Saving it to a yaml seems unreliable... it can't get checked in to version control, cause then migrations wouldn't be run again on each developers laptop, or in production. So if it's ignored, seems like it could get overwritten or removed in production, depending on the deploy setup.

I need a simple migration gem that you can just drop in and go. So I was wondering how open you are to modifying this one to be "zero config" and focus specifically on chore type migrations?

I'm more than willing to help out with PRs as well.

**Comment by zaccari** [comment]
Hey @ridiculous, thanks for looking at this, I really like what you outlined. 

The `every` option of running tasks multiple times was just an experimental item I added when I threw this together. I agree that it does not add much value and can be removed.

I think the zero-configuration approach of using a specific namespace is nice. I may look at an alternative name for `chores`, as it sounds like something that is periodically done. Perhaps `migrations` would work? I am open to any suggestions here.

And yeah, I went with YAML initially just to get something working. Persisting to the database is definitely where I think this gem should head to.

To answer your question - I am very open to modifying the gem. I've got some free time coming up later this week and should be able to get most of these items knocked out, including adding rspec tests.

**Comment by ridiculous** [comment]
Awesome! :sparkles: :sparkles: I actually like what you already have as the namespace: `rake tasks:migrate`. I had it setup to just exclude the `migrate` task from the rest of the namespaced tasks. But I think that reads nicely.

**Comment by zaccari** [comment]
Removed the `every` option here in #2

**Comment by zaccari** [comment]
Hey @ridiculous, I was able to spend some time on this gem and got these items done:
- Changed the name to `rake-task-migration`
- Removed the config and manifest files
- Added the database backup
- Added support for custom namespace and table name
- Added rspec tests
- Hooked into travis-ci and codeclimate

When you get a chance please try out the updates and let me know what you think.

**Comment by ridiculous** [comment]
Wow, good progress! I'll try it out this weekend. The readme says this is how you run it: 

`rake tasks:migrate`

But is that correct? Because the default namespace is "migrations", so intuitively that would be the way to call it ... Also, I noticed you didn't quite update the directory structure correctly when renaming. It should following the [Rubygems naming convention](http://guides.rubygems.org/name-your-gem/).

How to do you feel about adding this to the engine so that migrations are seamlessly integrated into the parent app, and we can skip the `rake task_migration:install:migrations` step:

``` ruby
initializer "rake.task.migrations.register_migrations" do
  config.paths["db/migrate"].expanded.each do |expanded_path|
    Rails.application.config.paths["db/migrate"] << expanded_path
  end
end
```

**Comment by ridiculous** [comment]
What about using `rake task:migrations` as the way to run it? Makes the most sense based on the name...

**Comment by zaccari** [comment]
Thanks. I will look into the naming conventions this weekend.

As for the rake task, the namespace is arbitrary and can be configured. I prefer to follow the example other migrators use with `name:migrate`

``` bash
$ bundle exec rake db:migrate
$ bundle exec rake seed:migrate
$ bundle exec rake tasks:migrate
```

I'm open `task:migrate` as a possible alternative.

Thanks for the db migration suggestion, I've added it as issue #10

**Comment by ridiculous** [comment]
cool, sounds good! :+1:
