### ISSUE TITLE
Tasks Running Multiple Times

### ISSUE THREAD

**Issue by danjohnson3141** [mzaccari/rake-task-migrations#14]
My team and I tried to use this gem to simplify our deployment process but we encountered our sample rake tasks running even when it was already in the table. I can't imagine this is the intended behavior because that would be very much unlike how database migrations behave.

Are we using this gem incorrectly or do we misunderstand how this gem works?

**Comment by zaccari** [comment]
That's very strange. When you get a chance, could you provide an example of the rake task that fails? I just tested this with Rails 6 on Ruby 2.7 with a simple `puts` task and see that it's not running twice:

<img width="713" alt="Screen Shot 2020-08-03 at 8 41 40 PM" src="https://user-images.githubusercontent.com/646363/89240380-f132c300-d5c9-11ea-9601-2415bef0fb07.png">

**Comment by danjohnson3141** [comment]
Thanks so much for the quick reply Michael. Let me do another fresh test with your gem. I'm inclined to think it was a mistake on our side. I just wanted to verify it worked the way we thought it should. And it sounds like it does. If we still can't get it to not re-run tasks I'll get back to you with more details. Otherwise I'll close this.
Take care!

**Comment by danjohnson3141** [comment]
It appears we are still experiencing tasks being re-ran. 

One thing I should have mentioned is that we have **multiple tenants** which means we have **multiple DB schemas** (in Postgres). I wonder if that is causing the issue. One of our developers is looking into that angle.

**Comment by nrsantamaria** [comment]
@zaccari we were able to resolve the issue with having multiple tenants by specifying the tenant in the config file you recommend setting up for customizations.
```
Rake::TaskMigration.config do |config|
  config.migration_table_name = '<TENANT_NAME_HERE>.rake_task_migrations'
end
```

Thanks so much for your quick response! This issue can be closed out.
